Updated Jenksins file to use release-it to manage versions numbers with git tags

diff --git a/stable/java-gradle/Jenkinsfile b/stable/java-gradle/Jenkinsfile
--- a/stable/java-gradle/Jenkinsfile
+++ b/stable/java-gradle/Jenkinsfile
@@ -21,10 +21,21 @@ def buildAgentName(String jobNameWithNamespace, String buildNumber, String names
 }
 
 def removeNamespaceFromJobName(String jobName, String namespace) {
-    return jobName.replaceAll(namespace + "-", "");
+    return jobName.replaceAll(namespace + "-", "").replaceAll(jobName + "/", "");
 }
 
+def buildSecretName(String jobNameWithNamespace, String namespace) {
+    return jobNameWithNamespace.replaceAll(namespace + "/", "").toLowerCase();
+}
+
+def secretName = buildSecretName(env.JOB_NAME, env.NAMESPACE)
+println "Job name: ${env.JOB_NAME}"
+println "Secret name: ${secretName}"
+
+def abortedBuild = false
+
 def buildLabel = buildAgentName(env.JOB_NAME, env.BUILD_NUMBER, env.NAMESPACE);
+def branch = env.BRANCH ?: "master"
 def namespace = env.NAMESPACE ?: "dev"
 def cloudName = env.CLOUD_NAME == "openshift" ? "openshift" : "kubernetes"
 def workingDir = "/home/jenkins/agent"
@@ -58,7 +69,7 @@ spec:
         - name: SONAR_USER_HOME
           value: ${workingDir}
     - name: node
-      image: node:11-stretch
+      image: node:12-stretch
       tty: true
       command: ["/bin/bash"]
       workingDir: ${workingDir}
@@ -75,6 +86,8 @@ spec:
       env:
         - name: HOME
           value: ${workingDir}
+        - name: BRANCH
+          value: ${branch}
     - name: ibmcloud
       image: docker.io/garagecatalyst/ibmcloud-dev:1.0.8
       tty: true
@@ -119,22 +132,26 @@ spec:
 """
 ) {
     node(buildLabel) {
-        container(name: 'node', shell: '/bin/bash') {
-            checkout scm
-            stage('Setup') {
-                sh '''#!/bin/bash
-                    # Export project name, version, and build number to ./env-config
-                    IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed "s/_/-/g")
-                    echo "IMAGE_NAME=${IMAGE_NAME}" > ./env-config
-                    npm run env | grep "^npm_package_version" | sed "s/npm_package_version/IMAGE_VERSION/g" >> ./env-config
-                    echo "BUILD_NUMBER=${BUILD_NUMBER}" >> ./env-config
-                    cat ./env-config
-                '''
-            }
-        }
+    try {
         container(name: 'jdk11', shell: '/bin/bash') {
+            checkout scm
+            try {
+                stage('Check for changes') {
+                    sh '''#!/bin/bash
+                        echo "Changed files in commit:"
+                        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD))
+                        echo "${CHANGED_FILES}"
 
-                stage('Build') {
+                        if [[ "${CHANGED_FILES}" == "package.json" ]]; then
+                          exit 1
+                        fi
+                    '''
+                }
+            } catch (e) {
+                abortedBuild = true
+                throw e;
+            }
+            stage('Build') {
                 sh '''
                     ./gradlew assemble --no-daemon
                 '''
@@ -156,6 +173,29 @@ spec:
                 '''
             }
         }
+        container(name: 'node', shell: '/bin/bash') {
+            stage('Tag release') {
+                withCredentials([usernamePassword(credentialsId: secretName, passwordVariable: 'GIT_AUTH_PWD', usernameVariable: 'GIT_AUTH_USER')]) {
+                    sh '''#!/bin/bash
+
+                        git checkout ${BRANCH}
+                        git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
+
+                        git config --global user.name "Jenkins Pipeline"
+                        git config --global user.email "jenkins@ibmcloud.com"
+                        git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
+
+                        npm i -g release-it
+
+                        release-it patch --ci --no-npm --git.tagName='v${version}' \
+                          --hooks.after:release='echo "IMAGE_VERSION=${version}" > ./env-config; echo "IMAGE_NAME=${repo.project}" >> ./env-config' \
+                          --verbose
+
+                        cat ./env-config
+                    '''
+                }
+            }
+        }
         container(name: 'ibmcloud', shell: '/bin/bash') {
             stage('Build image') {
                 sh '''#!/bin/bash
@@ -167,11 +207,6 @@ spec:
                     ibmcloud cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION} .
                     if [[ $? -ne 0 ]]; then
                       exit 1
-                    fi
-
-                    if [[ -n "${BUILD_NUMBER}" ]]; then
-                        echo -e "BUILDING CONTAINER IMAGE: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}-${BUILD_NUMBER}"
-                        ibmcloud cr image-tag ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION} ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}-${BUILD_NUMBER}
                     fi
                 '''
             }
@@ -194,10 +229,6 @@ spec:
                     RELEASE_NAME="${IMAGE_NAME}"
                     echo "RELEASE_NAME: $RELEASE_NAME"
 
-                    if [[ -n "${BUILD_NUMBER}" ]]; then
-                      IMAGE_VERSION="${IMAGE_VERSION}-${BUILD_NUMBER}"
-                    fi
-                    
                     echo "INITIALIZING helm with client-only (no Tiller)"
                     helm init --client-only 1> /dev/null 2> /dev/null
                     
@@ -272,10 +303,6 @@ spec:
 
                 . ./env-config
 
-                if [[ -n "${BUILD_NUMBER}" ]]; then
-                  IMAGE_BUILD_VERSION="${IMAGE_VERSION}-${BUILD_NUMBER}"
-                fi
-
                 if [[ -z "${ARTIFACTORY_ENCRPT}" ]]; then
                     echo "Encrption key not available for Jenkins pipeline, please add it to the artifactory-access"
                     exit 1
@@ -293,7 +320,7 @@ spec:
                 fi;
 
                 # Package Helm Chart
-                helm package --version ${IMAGE_BUILD_VERSION} ${CHART_ROOT}/${IMAGE_NAME}
+                helm package --version ${IMAGE_VERSION} ${CHART_ROOT}/${IMAGE_NAME}
 
                 # Get the index and re index it with current Helm Chart
                 curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_ENCRPT} -O "${URL}/${REGISTRY_NAMESPACE}/index.yaml"
@@ -310,7 +337,7 @@ spec:
                 fi;
 
                 # Persist the Helm Chart in Artifactory for us by ArgoCD
-                curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_ENCRPT} -i -vvv -T ${IMAGE_NAME}-${IMAGE_BUILD_VERSION}.tgz "${URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}-${IMAGE_BUILD_VERSION}.tgz"
+                curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_ENCRPT} -i -vvv -T ${IMAGE_NAME}-${IMAGE_VERSION}.tgz "${URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}-${IMAGE_VERSION}.tgz"
 
                 # Persist the Helm Chart in Artifactory for us by ArgoCD
                 curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_ENCRPT} -i -vvv -T index.yaml "${URL}/${REGISTRY_NAMESPACE}/index.yaml"
@@ -336,10 +363,6 @@ spec:
 
                     . ./env-config
 
-                    if [[ -n "${BUILD_NUMBER}" ]]; then
-                      IMAGE_BUILD_VERSION="${IMAGE_VERSION}-${BUILD_NUMBER}"
-                    fi
-
                     # This email is not used and is not valid, you can ignore but git requires it
                     git config --global user.email "jenkins@ibmcloud.com"
                     git config --global user.name "Jenkins Pipeline"
@@ -353,16 +376,25 @@ spec:
                     cat "./${IMAGE_NAME}/requirements.yaml"
 
                     npm i -g @garage-catalyst/ibm-garage-cloud-cli
-                    igc yq w ./${IMAGE_NAME}/requirements.yaml "dependencies[?(@.name == '${IMAGE_NAME}')].version" ${IMAGE_BUILD_VERSION} -i
+                    igc yq w ./${IMAGE_NAME}/requirements.yaml "dependencies[?(@.name == '${IMAGE_NAME}')].version" ${IMAGE_VERSION} -i
 
                     echo "Requirements after update"
                     cat "./${IMAGE_NAME}/requirements.yaml"
 
                     git add -u
-                    git commit -m "Updates ${IMAGE_NAME} to ${IMAGE_BUILD_VERSION}"
+                    git commit -m "Updates ${IMAGE_NAME} to ${IMAGE_VERSION}"
                     git push -v
                 '''
             }
         }
+    } catch (e) {
+        if (abortedBuild) {
+            currentBuild.result = 'ABORTED'
+            echo('Aborting build');
+            return;
+        }
+
+        throw e;
+    }
     }
 }
