Updates to all pipelines
- Updates ingress to use networking.k8s.io apiGroup instead of deprecated extensions
- Error handling for Artifactory

diff --git a/stable/java-maven/Jenkinsfile b/stable/java-maven/Jenkinsfile
--- a/stable/java-maven/Jenkinsfile
+++ b/stable/java-maven/Jenkinsfile
@@ -203,13 +203,20 @@ spec:
                     set -x
                     set -e
 
+                    if [[ -z "$GIT_AUTH_USER" ]] || [[ -z "$GIT_AUTH_PWD" ]]; then
+                      echo "Git credentials not found. The pipeline expects to find them in a secret named 'git-credentials'."
+                      echo "  Update your CLI and register the pipeline again"
+                      exit 1
+                    fi
+                    git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
+
                     git fetch origin ${BRANCH}
+                    git fetch --tags
                     git checkout ${BRANCH}
                     git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
 
                     git config --global user.name "Jenkins Pipeline"
                     git config --global user.email "jenkins@ibmcloud.com"
-                    git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
 
                     mkdir -p ~/.npm
                     npm config set prefix ~/.npm
@@ -240,8 +247,8 @@ spec:
                     set -e
                     . ./env-config
 
-		    echo TLSVERIFY=${TLSVERIFY}
-		    echo CONTEXT=${CONTEXT}
+                    echo TLSVERIFY=${TLSVERIFY}
+                    echo CONTEXT=${CONTEXT}
 
                     APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}"
 
@@ -320,7 +327,7 @@ spec:
                         ROUTE_HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
                         URL="https://${ROUTE_HOST}"
                     else
-                        INGRESS_HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
+                        INGRESS_HOST=$(kubectl get ingress.networking.k8s.io/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
                         URL="http://${INGRESS_HOST}"
                     fi
 
@@ -348,7 +355,7 @@ spec:
                 . ./env-config
 
                 if [[ -z "${ARTIFACTORY_ENCRYPT}" ]]; then
-                    echo "Encrption key not available for Jenkins pipeline, please add it to the artifactory-access"
+                    echo "It looks like your Artifactory installation is not complete. Please complete the steps found here - http://ibm.biz/complete-setup"
                     exit 1
                 fi
 
@@ -412,6 +419,8 @@ spec:
                     git config --global user.name "Jenkins Pipeline"
 
                     GIT_URL="https://${username}:${password}@${host}/${org}/${repo}"
+
+                    echo "Cloning repo: https://${username}:xxxx@${host}/${org}/${repo}"
 
                     git clone -b ${branch} ${GIT_URL} gitops_cd
                     cd gitops_cd
