add changes for sonar-cli, actions, and readme'

diff --git a/stable/appmod-liberty/Jenkinsfile b/stable/appmod-liberty/Jenkinsfile
--- a/stable/appmod-liberty/Jenkinsfile
+++ b/stable/appmod-liberty/Jenkinsfile
@@ -58,16 +58,8 @@ spec:
         - configMapRef:
             name: pactbroker-config
             optional: true
-        - configMapRef:
-            name: sonarqube-config
-            optional: true
-        - secretRef:
-            name: sonarqube-access
-            optional: true
       env:
         - name: HOME
-          value: ${workingDir}
-        - name: SONAR_USER_HOME
           value: ${workingDir}
     - name: node
       image: node:12-stretch
@@ -78,12 +70,6 @@ spec:
         - configMapRef:
             name: pactbroker-config
             optional: true
-        - configMapRef:
-            name: sonarqube-config
-            optional: true
-        - secretRef:
-            name: sonarqube-access
-            optional: true
       env:
         - name: HOME
           value: ${workingDir}
@@ -92,12 +78,12 @@ spec:
         - name: GIT_AUTH_USER
           valueFrom:
             secretKeyRef:
-              name: ${secretName}
+              name: git-credentials
               key: username
         - name: GIT_AUTH_PWD
           valueFrom:
             secretKeyRef:
-              name: ${secretName}
+              name: git-credentials
               key: password
     - name: buildah
       image: quay.io/buildah/stable:v1.11.0
@@ -166,6 +152,8 @@ spec:
           value: ${namespace}
         - name: BUILD_NUMBER
           value: ${env.BUILD_NUMBER}
+        - name: BRANCH
+          value: ${branch}
     - name: trigger-cd
       image: docker.io/garagecatalyst/ibmcloud-dev:1.0.10
       tty: true
@@ -175,8 +163,26 @@ spec:
         - name: HOME
           value: /home/devops
       envFrom:
-        - secretRef:
+        - configMapRef:
             name: gitops-cd-secret
+            optional: true
+        - configMapRef:
+            name: gitops-repo
+            optional: true
+        - secretRef:
+            name: git-credentials
+            optional: true
+    - name: sonarqube-cli
+      image: docker.io/sonarsource/sonar-scanner-cli:4.4
+      tty: true
+      command: ["/bin/bash"]
+      workingDir: ${workingDir}
+      envFrom:
+        - configMapRef:
+            name: sonarqube-config
+            optional: true
+        - secretRef:
+            name: sonarqube-access
             optional: true
 """
 ) {
@@ -194,19 +200,62 @@ spec:
                 '''
             }
         }
+        container(name: 'sonarqube-cli', shell: '/bin/bash') {
+            stage('Sonar scan') {
+                sh '''#!/bin/bash
+
+                if ! command -v sonar-scanner &> /dev/null
+                then
+                    echo "Skipping SonarQube step, no task defined"
+                    exit 0
+                fi
+
+                if [ -n "${SONARQUBE_URL}" ]; then
+                  sonar-scanner \
+                    -Dsonar.login=${SONARQUBE_USER} \
+                    -Dsonar.password=${SONARQUBE_PASSWORD} \
+                    -Dsonar.host.url=${SONARQUBE_URL} 
+                else 
+                    echo "Skipping Sonar Qube step"
+                fi
+
+                '''
+            }
+        }
         container(name: 'node', shell: '/bin/bash') {
             stage('Tag release') {
                 sh '''#!/bin/bash
                     set -x
                     set -e
 
-                    git fetch origin ${BRANCH} --tags
-                    git checkout ${BRANCH}
+                    if [[ -z "$GIT_AUTH_USER" ]] || [[ -z "$GIT_AUTH_PWD" ]]; then
+                      echo "Git credentials not found. The pipeline expects to find them in a secret named 'git-credentials'."
+                      echo "  Update your CLI and register the pipeline again"
+                      exit 1
+                    fi
+
+                    git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
+
+                    git checkout -b ${BRANCH} --track origin/${BRANCH}
                     git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
 
-                    git config --global user.name "Jenkins Pipeline"
-                    git config --global user.email "jenkins@ibmcloud.com"
-                    git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
+                    git fetch
+                    git fetch --tags
+                    git tag -l
+
+                    COMMIT_HASH=$(git rev-parse HEAD)
+                    git checkout -b ${BRANCH} --track origin/${BRANCH}
+                    git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
+                    git reset --hard ${COMMIT_HASH}
+
+                    if [[ "${BRANCH}" == "master" ]] && [[ $(git describe --tag `git rev-parse HEAD`) =~ (^[0-9]+.[0-9]+.[0-9]+$) ]] || \
+                       [[ $(git describe --tag `git rev-parse HEAD`) =~ (^[0-9]+.[0-9]+.[0-9]+-${BRANCH}[.][0-9]+$) ]]
+                    then
+                        echo "Latest commit is already tagged"
+                        echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" > ./env-config
+                        echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" >> ./env-config
+                        exit 0
+                    fi
 
                     mkdir -p ~/.npm
                     npm config set prefix ~/.npm
@@ -220,12 +269,16 @@ spec:
                     release-it patch ${PRE_RELEASE} \
                       --ci \
                       --no-npm \
+                      --no-git.push \
                       --no-git.requireCleanWorkingDir \
                       --verbose \
                       -VV
 
+                    git push --follow-tags -v
+
                     echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" > ./env-config
                     echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" >> ./env-config
+                    echo "REPO_URL=$(git config --get remote.origin.url)" >> ./env-config
 
                     cat ./env-config
                 '''
@@ -237,8 +290,8 @@ spec:
                     set -e
                     . ./env-config
 
-		    echo TLSVERIFY=${TLSVERIFY}
-		    echo CONTEXT=${CONTEXT}
+		            echo TLSVERIFY=${TLSVERIFY}
+		            echo CONTEXT=${CONTEXT}
 
                     APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}"
 
@@ -288,6 +341,8 @@ spec:
 
                     # Update helm chart with repository and tag values
                     cat ${CHART_PATH}/values.yaml | \
+                        yq w - vcsInfo.repoUrl "${REPO_URL}" | \
+                        yq w - vcsInfo.branch "${BRANCH}" | \
                         yq w - image.repository "${IMAGE_REPOSITORY}" | \
                         yq w - image.tag "${IMAGE_VERSION}" | \
                         yq w - ingress.enabled "${INGRESS_ENABLED}" | \
@@ -317,21 +372,27 @@ spec:
                         ROUTE_HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
                         URL="https://${ROUTE_HOST}"
                     else
-                        INGRESS_HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
+                        INGRESS_HOST=$(kubectl get ingress.networking.k8s.io/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
                         URL="http://${INGRESS_HOST}"
                     fi
 
+                    sleep_countdown=5
+
                     # sleep for 10 seconds to allow enough time for the server to start
-                    sleep 30
+                    sleep 10
+                    echo "Health check start"
+                    while [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
+                        sleep 30
+                        echo "Health check failure. Remaining retries: $sleep_countdown"
+                        sleep_countdown=$((sleep_countdown-1))
+                        if [[ $sleep_countdown -eq 0 ]]; then
+                                echo "Could not reach health endpoint: ${URL}/health"
+                                exit 1;
+                        fi
+                    done
 
-                    if [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]]; then
-                        echo "Successfully reached health endpoint: ${URL}/health"
-                        echo "====================================================================="
-                    else
-                        echo "Could not reach health endpoint: ${URL}/health"
-                        exit 1
-                    fi
-
+                    echo "Successfully reached health endpoint: ${URL}/health"
+                    echo "====================================================================="
                 '''
             }
             stage('Package Helm Chart') {
@@ -345,7 +406,7 @@ spec:
                 . ./env-config
 
                 if [[ -z "${ARTIFACTORY_ENCRYPT}" ]]; then
-                    echo "Encrption key not available for Jenkins pipeline, please add it to the artifactory-access"
+                    echo "It looks like your Artifactory installation is not complete. Please complete the steps found here - http://ibm.biz/complete-setup"
                     exit 1
                 fi
 
diff --git a/stable/java-gradle/Jenkinsfile b/stable/java-gradle/Jenkinsfile
--- a/stable/java-gradle/Jenkinsfile
+++ b/stable/java-gradle/Jenkinsfile
@@ -58,16 +58,8 @@ spec:
         - configMapRef:
             name: pactbroker-config
             optional: true
-        - configMapRef:
-            name: sonarqube-config
-            optional: true
-        - secretRef:
-            name: sonarqube-access
-            optional: true
       env:
         - name: HOME
-          value: ${workingDir}
-        - name: SONAR_USER_HOME
           value: ${workingDir}
     - name: node
       image: node:12-stretch
@@ -78,12 +70,6 @@ spec:
         - configMapRef:
             name: pactbroker-config
             optional: true
-        - configMapRef:
-            name: sonarqube-config
-            optional: true
-        - secretRef:
-            name: sonarqube-access
-            optional: true
       env:
         - name: HOME
           value: ${workingDir}
@@ -92,15 +78,17 @@ spec:
         - name: GIT_AUTH_USER
           valueFrom:
             secretKeyRef:
-              name: ${secretName}
+              name: git-credentials
               key: username
+              optional: true
         - name: GIT_AUTH_PWD
           valueFrom:
             secretKeyRef:
-              name: ${secretName}
+              name: git-credentials
               key: password
+              optional: true
     - name: buildah
-      image: quay.io/buildah/stable:v1.9.2
+      image: quay.io/buildah/stable:v1.9.0
       tty: true
       command: ["/bin/bash"]
       workingDir: ${workingDir}
@@ -172,8 +160,10 @@ spec:
           value: ${namespace}
         - name: BUILD_NUMBER
           value: ${env.BUILD_NUMBER}
+        - name: BRANCH
+          value: ${branch}
     - name: trigger-cd
-      image: docker.io/garagecatalyst/ibmcloud-dev:1.0.8
+      image: docker.io/garagecatalyst/ibmcloud-dev:1.0.10
       tty: true
       command: ["/bin/bash"]
       workingDir: ${workingDir}
@@ -181,8 +171,26 @@ spec:
         - name: HOME
           value: /home/devops
       envFrom:
-        - secretRef:
+        - configMapRef:
             name: gitops-cd-secret
+            optional: true
+        - configMapRef:
+            name: gitops-repo
+            optional: true
+        - secretRef:
+            name: git-credentials
+            optional: true
+    - name: sonarqube-cli
+      image: docker.io/sonarsource/sonar-scanner-cli:4.4
+      tty: true
+      command: ["/bin/bash"]
+      workingDir: ${workingDir}
+      envFrom:
+        - configMapRef:
+            name: sonarqube-config
+            optional: true
+        - secretRef:
+            name: sonarqube-access
             optional: true
 """
 ) {
@@ -192,6 +200,7 @@ spec:
             stage('Setup') {
                 sh '''
                     echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" > ./env-config
+                    echo "REPO_URL=$(git config --get remote.origin.url)" >> ./env-config
 
                     chmod a+rw ./env-config
                 '''
@@ -206,27 +215,25 @@ spec:
                     ./gradlew testClasses --no-daemon
                 '''
             }
+        }
+        container(name: 'sonarqube-cli', shell: '/bin/bash') {
             stage('Sonar scan') {
                 sh '''#!/bin/bash
 
-                if [[ -z "${SONARQUBE_URL}" ]]; then
-                  echo "Skipping Sonar Qube step as Sonar Qube not installed or configured"
-                  exit 0
-                fi
-
-                if ./gradlew tasks --all | grep -Eq "^sonarqube"; then
-                    echo "SonarQube task found"
-                else
+                if ! command -v sonar-scanner &> /dev/null
+                then
                     echo "Skipping SonarQube step, no task defined"
                     exit 0
                 fi
 
-                ./gradlew \
-                  -Dsonar.login=${SONARQUBE_USER} \
-                  -Dsonar.password=${SONARQUBE_PASSWORD} \
-                  -Dsonar.host.url=${SONARQUBE_URL} \
-                  -Psonar.projectName=${IMAGE_NAME} \
-                  sonarqube
+                if [ -n "${SONARQUBE_URL}" ]; then
+                  sonar-scanner \
+                    -Dsonar.login=${SONARQUBE_USER} \
+                    -Dsonar.password=${SONARQUBE_PASSWORD} \
+                    -Dsonar.host.url=${SONARQUBE_URL} 
+                else 
+                    echo "Skipping Sonar Qube step"
+                fi
                 '''
             }
         }
@@ -236,13 +243,34 @@ spec:
                     set -x
                     set -e
 
-                    git fetch origin ${BRANCH} --tags
-                    git checkout ${BRANCH}
+                    if [[ -z "$GIT_AUTH_USER" ]] || [[ -z "$GIT_AUTH_PWD" ]]; then
+                      echo "Git credentials not found. The pipeline expects to find them in a secret named 'git-credentials'."
+                      echo "  Update your CLI and register the pipeline again"
+                      exit 1
+                    fi
+
+                    git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
+
+                    git fetch
+                    git fetch --tags
+                    git tag -l
+
+                    COMMIT_HASH=$(git rev-parse HEAD)
+                    git checkout -b ${BRANCH} --track origin/${BRANCH}
                     git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
+                    git reset --hard ${COMMIT_HASH}
 
                     git config --global user.name "Jenkins Pipeline"
                     git config --global user.email "jenkins@ibmcloud.com"
-                    git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
+
+                    if [[ "${BRANCH}" == "master" ]] && [[ $(git describe --tag `git rev-parse HEAD`) =~ (^[0-9]+.[0-9]+.[0-9]+$) ]] || \
+                       [[ $(git describe --tag `git rev-parse HEAD`) =~ (^[0-9]+.[0-9]+.[0-9]+-${BRANCH}[.][0-9]+$) ]]
+                    then
+                        echo "Latest commit is already tagged"
+                        echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" > ./env-config
+                        echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" >> ./env-config
+                        exit 0
+                    fi
 
                     mkdir -p ~/.npm
                     npm config set prefix ~/.npm
@@ -256,11 +284,16 @@ spec:
                     release-it patch ${PRE_RELEASE} \
                       --ci \
                       --no-npm \
+                      --no-git.push \
                       --no-git.requireCleanWorkingDir \
                       --verbose \
                       -VV
 
-                    echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" >> ./env-config
+                    git push --follow-tags -v
+
+                    echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" > ./env-config
+                    echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" >> ./env-config
+                    echo "REPO_URL=$(git config --get remote.origin.url)" >> ./env-config
 
                     cat ./env-config
                 '''
@@ -311,7 +344,7 @@ spec:
 
                     echo "INITIALIZING helm with client-only (no Tiller)"
                     helm init --client-only 1> /dev/null 2> /dev/null
-                    
+
                     echo "CHECKING CHART (lint)"
                     helm lint ${CHART_PATH}
 
@@ -327,6 +360,8 @@ spec:
 
                     # Update helm chart with repository and tag values
                     cat ${CHART_PATH}/values.yaml | \
+                        yq w - vcsInfo.repoUrl "${REPO_URL}" | \
+                        yq w - vcsInfo.branch "${BRANCH}" | \
                         yq w - image.repository "${IMAGE_REPOSITORY}" | \
                         yq w - image.tag "${IMAGE_VERSION}" | \
                         yq w - ingress.enabled "${INGRESS_ENABLED}" | \
@@ -340,10 +375,10 @@ spec:
                         --namespace ${ENVIRONMENT_NAME} \
                         --set ingress.tlsSecretName="${TLS_SECRET_NAME}" \
                         --set ingress.subdomain="${INGRESS_SUBDOMAIN}" > ./release.yaml
-                    
+
                     echo -e "Generated release yaml for: ${CLUSTER_NAME}/${ENVIRONMENT_NAME}."
                     cat ./release.yaml
-                    
+
                     echo -e "Deploying into: ${CLUSTER_NAME}/${ENVIRONMENT_NAME}."
                     kubectl apply -n ${ENVIRONMENT_NAME} -f ./release.yaml --validate=false
                 '''
@@ -353,24 +388,38 @@ spec:
                     . ./env-config
 
                     if [[ "${CLUSTER_TYPE}" == "openshift" ]]; then
-                        ROUTE_HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
-                        URL="https://${ROUTE_HOST}"
+                        PROTOCOL="https"
+                        HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
+                        PORT="443"
                     else
-                        INGRESS_HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
-                        URL="http://${INGRESS_HOST}"
+                        PROTOCOL="http"
+                        HOST=$(kubectl get ingress.networking.k8s.io/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
+                        PORT="80"
                     fi
+
+                    echo "PROTOCOL=${PROTOCOL}" >> ./env-config
+                    echo "HOST=${HOST}" >> ./env-config
+                    echo "PORT=${PORT}" >> ./env-config
+
+                    URL="${PROTOCOL}://${HOST}"
+
+                    sleep_countdown=5
 
                     # sleep for 10 seconds to allow enough time for the server to start
-                    sleep 30
+                    sleep 10
+                    echo "Health check start"
+                    while [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
+                        sleep 30
+                        echo "Health check failure. Remaining retries: $sleep_countdown"
+                        sleep_countdown=$((sleep_countdown-1))
+                        if [[ $sleep_countdown -eq 0 ]]; then
+                                echo "Could not reach health endpoint: ${URL}/health"
+                                exit 1;
+                        fi
+                    done
 
-                    if [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]]; then
-                        echo "Successfully reached health endpoint: ${URL}/health"
-                        echo "====================================================================="
-                    else
-                        echo "Could not reach health endpoint: ${URL}/health"
-                        exit 1
-                    fi
-
+                    echo "Successfully reached health endpoint: ${URL}/health"
+                    echo "====================================================================="
                 '''
             }
         }
@@ -384,6 +433,13 @@ spec:
 
                     set -x
                     . ./env-config
+
+                    if ./gradlew tasks --all | grep -Eq "^pactVerify"; then
+                        echo "Pact Verify task found"
+                    else
+                        echo "Skipping Pact Verify step, no task defined"
+                        exit 0
+                    fi
 
                     ./gradlew pactVerify \
                       -PpactBrokerUrl=${PACTBROKER_URL} \
@@ -406,7 +462,7 @@ spec:
                 . ./env-config
 
                 if [[ -z "${ARTIFACTORY_ENCRYPT}" ]]; then
-                    echo "Encrption key not available for Jenkins pipeline, please add it to the artifactory-access"
+                    echo "It looks like your Artifactory installation is not complete. Please complete the steps found here - http://ibm.biz/complete-setup"
                     exit 1
                 fi
 
diff --git a/stable/nodejs/Jenkinsfile b/stable/nodejs/Jenkinsfile
--- a/stable/nodejs/Jenkinsfile
+++ b/stable/nodejs/Jenkinsfile
@@ -59,12 +59,6 @@ spec:
         - configMapRef:
             name: pactbroker-config
             optional: true
-        - configMapRef:
-            name: sonarqube-config
-            optional: true
-        - secretRef:
-            name: sonarqube-access
-            optional: true
       env:
         - name: HOME
           value: ${workingDir}
@@ -73,15 +67,17 @@ spec:
         - name: GIT_AUTH_USER
           valueFrom:
             secretKeyRef:
-              name: ${secretName}
+              name: git-credentials
               key: username
+              optional: true
         - name: GIT_AUTH_PWD
           valueFrom:
             secretKeyRef:
-              name: ${secretName}
+              name: git-credentials
               key: password
+              optional: true
     - name: buildah
-      image: quay.io/buildah/stable:v1.9.2
+      image: quay.io/buildah/stable:v1.9.0
       tty: true
       command: ["/bin/bash"]
       workingDir: ${workingDir}
@@ -151,6 +147,8 @@ spec:
           value: /home/devops
         - name: ENVIRONMENT_NAME
           value: ${env.NAMESPACE}
+        - name: BRANCH
+          value: ${branch}
     - name: trigger-cd
       image: docker.io/garagecatalyst/ibmcloud-dev:1.0.10
       tty: true
@@ -160,8 +158,26 @@ spec:
         - name: HOME
           value: /home/devops
       envFrom:
-        - secretRef:
+        - configMapRef:
             name: gitops-cd-secret
+            optional: true
+        - configMapRef:
+            name: gitops-repo
+            optional: true
+        - secretRef:
+            name: git-credentials
+            optional: true
+    - name: sonarqube-cli
+      image: docker.io/sonarsource/sonar-scanner-cli:4.4
+      tty: true
+      command: ["/bin/bash"]
+      workingDir: ${workingDir}
+      envFrom:
+        - configMapRef:
+            name: sonarqube-config
+            optional: true
+        - secretRef:
+            name: sonarqube-access
             optional: true
 """
 ) {
@@ -170,7 +186,7 @@ spec:
             checkout scm
             stage('Build') {
                 sh '''#!/bin/bash
-                    npm install
+                    npm install --unsafe-perm
                     npm run build --if-present
                 '''
             }
@@ -189,29 +205,62 @@ spec:
                     npm run pact:verify --if-present
                 '''
             }
+        }
+        container(name: 'sonarqube-cli', shell: '/bin/bash') {
             stage('Sonar scan') {
                 sh '''#!/bin/bash
 
-                if [[ -z "${SONARQUBE_URL}" ]]; then
-                  echo "Skipping Sonar Qube step as Sonar Qube not installed or configured"
-                  exit 0
+                if ! command -v sonar-scanner &> /dev/null
+                then
+                    echo "Skipping SonarQube step, no task defined"
+                    exit 0
                 fi
 
-                npm run sonarqube:scan --if-present
+                if [ -n "${SONARQUBE_URL}" ]; then
+                  sonar-scanner \
+                    -Dsonar.login=${SONARQUBE_USER} \
+                    -Dsonar.password=${SONARQUBE_PASSWORD} \
+                    -Dsonar.host.url=${SONARQUBE_URL} 
+                else 
+                    echo "Skipping Sonar Qube step"
+                fi
                 '''
             }
+        }
+        container(name: 'node', shell: '/bin/bash') {
             stage('Tag release') {
                 sh '''#!/bin/bash
                     set -x
                     set -e
 
-                    git fetch origin ${BRANCH} --tags
-                    git checkout ${BRANCH}
+                    if [[ -z "$GIT_AUTH_USER" ]] || [[ -z "$GIT_AUTH_PWD" ]]; then
+                      echo "Git credentials not found. The pipeline expects to find them in a secret named 'git-credentials'."
+                      echo "  Update your CLI and register the pipeline again"
+                      exit 1
+                    fi
+
+                    git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
+
+                    git fetch
+                    git fetch --tags
+                    git tag -l
+
+                    COMMIT_HASH=$(git rev-parse HEAD)
+                    git checkout -b ${BRANCH} --track origin/${BRANCH}
                     git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
+                    git reset --hard ${COMMIT_HASH}
 
                     git config --global user.name "Jenkins Pipeline"
                     git config --global user.email "jenkins@ibmcloud.com"
-                    git config --local credential.helper "!f() { echo username=\\$GIT_AUTH_USER; echo password=\\$GIT_AUTH_PWD; }; f"
+
+                    if [[ "${BRANCH}" == "master" ]] && [[ $(git describe --tag `git rev-parse HEAD`) =~ (^[0-9]+.[0-9]+.[0-9]+$) ]] || \
+                       [[ $(git describe --tag `git rev-parse HEAD`) =~ (^[0-9]+.[0-9]+.[0-9]+-${BRANCH}[.][0-9]+$) ]]
+                    then
+                        echo "Latest commit is already tagged"
+                        echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" > ./env-config
+                        echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" >> ./env-config
+                        exit 0
+                    fi
 
                     mkdir -p ~/.npm
                     npm config set prefix ~/.npm
@@ -225,12 +274,16 @@ spec:
                     release-it patch ${PRE_RELEASE} \
                       --ci \
                       --no-npm \
+                      --no-git.push \
                       --no-git.requireCleanWorkingDir \
                       --verbose \
                       -VV
 
+                    git push --follow-tags -v
+
                     echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" > ./env-config
                     echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" >> ./env-config
+                    echo "REPO_URL=$(git config --get remote.origin.url)" >> ./env-config
 
                     cat ./env-config
                 '''
@@ -301,6 +354,8 @@ spec:
                     cat ${CHART_PATH}/values.yaml | \
                         yq w - nameOverride "${IMAGE_NAME}" | \
                         yq w - fullnameOverride "${IMAGE_NAME}" | \
+                        yq w - vcsInfo.repoUrl "${REPO_URL}" | \
+                        yq w - vcsInfo.branch "${BRANCH}" | \
                         yq w - image.repository "${IMAGE_REPOSITORY}" | \
                         yq w - image.tag "${IMAGE_VERSION}" | \
                         yq w - ingress.enabled "${INGRESS_ENABLED}" | \
@@ -330,20 +385,27 @@ spec:
                         ROUTE_HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
                         URL="https://${ROUTE_HOST}"
                     else
-                        INGRESS_HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
+                        INGRESS_HOST=$(kubectl get ingress.networking.k8s.io/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
                         URL="http://${INGRESS_HOST}"
                     fi
 
-                    # sleep for 10 seconds to allow enough time for the server to start
-                    sleep 30
+                    sleep_countdown=5
 
-                    if [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]]; then
-                        echo "Successfully reached health endpoint: ${URL}/health"
-                        echo "====================================================================="
-                    else
-                        echo "Could not reach health endpoint: ${URL}/health"
-                        exit 1;
-                    fi;
+                    # sleep for 10 seconds to allow enough time for the server to start
+                    sleep 10
+                    echo "Health check start"
+                    while [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
+                        sleep 30
+                        echo "Health check failure. Remaining retries: $sleep_countdown"
+                        sleep_countdown=$((sleep_countdown-1))
+                        if [[ $sleep_countdown -eq 0 ]]; then
+                                echo "Could not reach health endpoint: ${URL}/health"
+                                exit 1;
+                        fi
+                    done
+
+                    echo "Successfully reached health endpoint: ${URL}/health"
+                    echo "====================================================================="
                 '''
             }
             stage('Package Helm Chart') {
@@ -357,7 +419,7 @@ spec:
                 . ./env-config
 
                 if [[ -z "${ARTIFACTORY_ENCRYPT}" ]]; then
-                    echo "Encrption key not available for Jenkins pipeline, please add it to the artifactory-access"
+                    echo "It looks like your Artifactory installation is not complete. Please complete the steps found here - http://ibm.biz/complete-setup"
                     exit 1
                 fi
 
